ignored:
  # Always tag the version of an image explicitly
  - DL3006
  # Last USER should not be root
  - DL3002 
  # Specify version with `dnf install -y <package>-<version>`.
  - DL3041 
  # Pin versions in pip. Instead of `pip install <package>` use `pip install
  - DL3013
